language: node_js
node_js: 10
os: osx
before_install: 
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - brew install yarn
install: yarn global add neon-cli && yarn install
before_script: neon build --release
script: node -e lib/index.js